local Game = require "game"
local qr = require "libs.qr"
local M = {}

local svg_cache, svg_count = {}, 0
local function qr_svg(url) -- encoding is cheap but the host view is re-rendered often; cache per URL
    if not svg_cache[url] then
        if svg_count > 20 then svg_cache, svg_count = {}, 0 end
        svg_cache[url], svg_count = qr.svg(url), svg_count + 1
    end
    return svg_cache[url]
end

---@param v View
local function qr_card(v)
    local info = {
        class = "qrinfo",
        p { "Join the same wifi, then scan or open:" },
        p { class = "url", esc(v.join_url) },
        div { class = "bigcode", v.code },
    }
    if v.alt_urls and #v.alt_urls > 0 then
        local alts = {}
        for _, u in ipairs(v.alt_urls) do alts[#alts + 1] = esc(u) end
        info[#info + 1] = p { class = "url", em { "Scan not working? Try: " .. table.concat(alts, "  ") } }
    end
    return div {
        class = "card qrcard",
        div { class = "qrrow",
            qr_svg(v.join_url), -- raw SVG string, generated by us (no user input in it)
            div(info),
        },
    }
end

local TITLES = { lobby = "LOBBY", night = "NIGHT", day = "DAY", over = "GAME OVER" }

---@param v View
---@param right any? something to put at the right edge of the bar (a button, the role chip)
---@return table
local function header(v, right)
    local title = TITLES[v.phase]
    if v.phase == "night" or v.phase == "day" then title = title .. " " .. v.round end
    return div { class = "bar", h2 { title }, right }
end

---@param list any[]
---@return table
local function col(list)
    local kids = { class = "col" }
    for _, c in ipairs(list) do kids[#kids + 1] = c end
    return div(kids)
end

---@param parts any[] columns
---@return table
local function cols(parts)
    local kids = { class = "cols" }
    for _, c in ipairs(parts) do kids[#kids + 1] = c end
    return div(kids)
end

---@param v View
---@param with_kick boolean
---@return HTMLElement
local function roster(v, with_kick)
    local title = ("Players %d"):format(#v.players)
    if with_kick then title = title .. (" \u{b7} min %d"):format(v.min_players) end
    local chips = { class = "chips" }
    for _, pl in ipairs(v.players) do
        local kids = { class = "chip " .. (pl.alive and "alive" or "dead"), esc(pl.name) }
        ---@diagnostic disable-next-line: assign-type-mismatch
        if pl.role then kids[#kids + 1] = em { Game.roles[pl.role].name } end
        if with_kick then
            ---@diagnostic disable-next-line: assign-type-mismatch
            kids[#kids + 1] = button { class = "x", title = "remove", onclick = ("act('kick', %d)"):format(pl.id), "\u{d7}" }
        end
        chips[#chips + 1] = span(kids)
    end
    if #v.players == 0 then chips[1] = em { "Nobody has joined yet." } end
    return div { class = "card", h3 { title }, div(chips) }
end

---The history box has a fixed height and scrolls (newest line on top).
---@param v View
---@return HTMLElement?
local function log_box(v)
    if #v.log == 0 then return nil end
    local lines = { class = "logbox" }
    for idx = #v.log, 1, -1 do lines[#lines + 1] = p { esc(v.log[idx]) } end
    return div { class = "card", h3 { "What happened" }, div(lines) }
end

---@param v View
---@return HTMLElement?
local function banner(v)
    if v.phase ~= "over" then return nil end
    return div { class = "card banner", h2 { v.winner == "village" and "The village wins!" or "The werewolves win!" } }
end

---"1 Werewolf · 1 Seer · 2 Villagers"
---@param deck { role: string, count: integer }[]
---@return HTMLElement
local function deck_line(deck)
    local names = {}
    for _, e in ipairs(deck) do
        local role = Game.roles[e.role]
        names[#names + 1] = ("%d %s"):format(e.count, e.count > 1 and (role.plural or role.name .. "s") or role.name)
    end
    return p { class = "inplay", em { "In play: " .. table.concat(names, " \u{b7} ") } }
end

---@param v View
---@return HTMLElement
local function info_card(v)
    local kids = { class = "card info", p { class = "blurb", Game.roles[v.you.role].blurb } }
    if v.deck then kids[#kids + 1] = deck_line(v.deck) end
    if not v.you.alive then kids[#kids + 1] = p { class = "dead-note", "You are dead. Watch quietly, no talking!" } end
    return div(kids)
end

---@param v View
---@return HTMLElement?
local function action_card(v)
    local a = v.action
    if not a then return nil end
    local kids = { class = "card action", h3 { class = "prompt", a.prompt } }
    if a.locked then
        -- one string, because the html lib puts a space between children
        kids[#kids + 1] = p { ("You chose %s. Waiting for dawn..."):format(tostring(strong { esc(a.chosen_name) })) }
    elseif a.verb then
        local grid = { class = "targets" }
        for _, t in ipairs(a.targets) do
            grid[#grid + 1] = button {
                class = (a.chosen == t.id) and "selected" or nil,
                onclick = ("act('%s', %d)"):format(a.verb, t.id),
                esc(t.name),
            }
        end
        if a.verb == "vote" and a.can_abstain then
            grid[#grid + 1] = button { class = (a.chosen == 0) and "selected wide" or "wide", onclick = "act('vote', 0)", "Abstain" }
        end
        if #grid == 0 then grid[1] = em { "There is nobody you can choose." } end
        kids[#kids + 1] = div(grid)
        if a.verb == "vote" then
            kids[#kids + 1] = p { class = "hint", em { v.progress.voted .. " of " .. v.progress.total .. " have voted." } }
        end
    end
    return div(kids)
end

---@param v View
---@return HTMLElement[]
local function private_cards(v)
    local out = {}
    if v.notes and #v.notes > 0 then
        local kids = { class = "card notes", h3 { "Your secret knowledge" } }
        for _, n in ipairs(v.notes) do kids[#kids + 1] = p { esc(n) } end
        out[#out + 1] = div(kids)
    end
    if v.pack and #v.pack > 0 then
        local kids = { class = "card notes", h3 { "The pack's choices" } }
        for _, e in ipairs(v.pack) do kids[#kids + 1] = p { esc(e.wolf) .. " wants " .. esc(e.target) } end
        out[#out + 1] = div(kids)
    end
    return out
end

---@param parts HTMLElement[]
---@param class string?
---@return string
local function assemble(parts, class)
    local list = { id = "view", class = class }
    for _, part in ipairs(parts) do list[#list + 1] = part end
    return tostring(div(list))
end

---@param v View
---@return string
function M.client(v)
    local chip = span { class = "rolechip " .. (v.you.team or ""), v.you.role and Game.roles[v.you.role].name or "" }
    if v.phase == "lobby" then chip = nil end
    local parts = { header(v, chip) }
    if v.phase == "lobby" then
        parts[#parts + 1] = div { class = "card", h3 { "You're in, " .. esc(v.you.name) .. "!" }, p { "Waiting for the host to start the game." } }
        parts[#parts + 1] = roster(v, false)
    else
        parts[#parts + 1] = banner(v)
        parts[#parts + 1] = info_card(v)
        parts[#parts + 1] = action_card(v)
        for _, c in ipairs(private_cards(v)) do parts[#parts + 1] = c end
        parts[#parts + 1] = roster(v, false)
        parts[#parts + 1] = log_box(v)
    end
    return assemble(parts, "client")
end

---One role of the lobby's "Roles" panel: name, how many get dealt, an on/off switch, and what it does.
---@param r RoleView
---@return HTMLElement
local function role_row(r)
    local head = { class = "rhead", span { class = "rname " .. r.team, r.name } }
    if r.count then head[#head + 1] = span { class = "count", "\u{d7}" .. r.count } end
    if r.core then
        head[#head + 1] = em { class = "always", "always" }
    else
        head[#head + 1] = button {
            class = r.active and "toggle on" or "toggle",
            onclick = ("toggleRole('%s', %d)"):format(r.key, r.active and 0 or 1),
            r.active and "On" or "Off",
        }
    end
    return div { class = r.active and "rolerow" or "rolerow off", div(head), p { class = "rblurb", r.blurb } }
end

---@param v View
---@return HTMLElement
local function roles_card(v)
    local kids = { class = "card", h3 { "Roles" } }
    for _, r in ipairs(v.roles) do kids[#kids + 1] = role_row(r) end
    if v.deck_error then kids[#kids + 1] = p { class = "err", esc(v.deck_error) } end
    return div(kids)
end

---One rule of the lobby's "Rules" panel. bool = switch, int = stepper, choice = click to cycle.
---@param r RuleView
---@return HTMLElement
local function rule_row(r)
    local control
    if r.kind == "bool" then
        control = button {
            class = r.value and "toggle on" or "toggle",
            onclick = ("setting('%s','%d')"):format(r.key, r.value and 0 or 1),
            r.display,
        }
    elseif r.kind == "int" then
        control = span {
            class = "stepper",
            button { onclick = ("setting('%s','%d')"):format(r.key, r.value - 1), disabled = r.value <= r.min or nil, "\u{2212}" },
            span { class = "val", r.display },
            button { onclick = ("setting('%s','%d')"):format(r.key, r.value + 1), disabled = r.value >= r.max or nil, "+" },
        }
    else
        local nxt = r.options[1].value
        for idx, o in ipairs(r.options) do
            if o.value == r.value then nxt = r.options[idx % #r.options + 1].value end
        end
        control = button { class = "toggle on", onclick = ("setting('%s','%s')"):format(r.key, nxt), r.display }
    end
    return div { class = r.relevant and "rule" or "rule dim", title = esc(r.help), span { class = "rlabel", r.label }, control }
end

---@param v View
---@return HTMLElement
local function rules_card(v)
    local kids = { class = "card", h3 { "Rules" } }
    for _, r in ipairs(v.rules) do kids[#kids + 1] = rule_row(r) end
    return div(kids)
end

---fragment for the shared host screen (public information only)
---@param v View
---@return string
function M.host(v)
    if v.phase == "lobby" then
        local start = button { class = "primary", title = ("Needs at least %d players"):format(v.min_players), onclick = "act('start')", "START GAME" }
        return assemble({
            header(v, start),
            cols {
                col { qr_card(v), roster(v, true) },
                col { roles_card(v) },
                col { rules_card(v) },
            },
        }, "host")
    end

    local status = { class = "card info" }
    if v.phase == "night" then
        status[#status + 1] = p { "Night falls. Everyone close your eyes and wait to be called by the host." }
    elseif v.phase == "day" then
        status[#status + 1] = p { "Discuss, then vote on your phones. Votes in: " .. v.progress.voted .. "/" .. v.progress.total }
    end
    if v.deck then status[#status + 1] = deck_line(v.deck) end
    local left = { banner(v) }
    if #status > 0 then left[#left + 1] = div(status) end
    left[#left + 1] = roster(v, false)

    local action = v.phase == "over"
        and button { class = "primary", onclick = "act('restart')", "PLAY AGAIN" }
        or button { class = "primary", onclick = "act('next')", "NEXT" }
    return assemble({
        header(v, action),
        cols { col(left), col { log_box(v) } },
    }, "host")
end

local CLIENT_JS = [==[
const q = new URLSearchParams(location.search);
const code = q.get('code') || '';
const auth = q.get('key')
    ? 'key=' + encodeURIComponent(q.get('key'))
    : 'token=' + encodeURIComponent(q.get('token') || '');
const app = document.getElementById('app');
let version = -1, busy = false, again = false, stopped = false;

// Swap in a new fragment, but keep the history box where the reader left it.
function swap(html) {
    const old = app.querySelector('.logbox');
    const top = old ? old.scrollTop : 0, height = old ? old.scrollHeight : 0;
    app.innerHTML = html;
    const log = app.querySelector('.logbox');
    if (log && top > 0) log.scrollTop = top + (log.scrollHeight - height); // new lines arrive on top
}

async function poll() {
    if (stopped) return;
    if (busy) { again = true; return; }
    busy = true;
    try {
        const r = await fetch('/api/view?code=' + code + '&' + auth + '&v=' + version, { cache: 'no-store' });
        if (r.status === 200) {            // something changed: swap in the new fragment
            swap(await r.text());
            version = Number(r.headers.get('X-Version'));
        } else if (r.status >= 400) {      // game gone / bad token: stop polling and say why
            stopped = true;
            app.textContent = await r.text();
        }                                  // 204 = nothing new
    } catch (e) { /* server busy or restarting: retry on the next tick */ }
    busy = false;
    if (again) { again = false; poll(); }
}

async function act(type, target, extra) {
    let url = '/api/action?code=' + code + '&' + auth + '&type=' + type + '&target=' + (target ?? '');
    for (const k in (extra || {})) url += '&' + k + '=' + encodeURIComponent(extra[k]);
    const r = await fetch(url, { method: 'POST' });
    if (!r.ok) alert(await r.text());
    poll();
}
const setting = (name, value) => act('set', null, { name, value });      // host: change a rule
const toggleRole = (name, on) => act('role', null, { name, value: on }); // host: enable/disable a role

setInterval(poll, 1000);
poll();
]==]

--- the static page shell for /host and /client; everything inside #app arrives via polling
function M.page(kind)
    return response {
        body = WRAPPER {
            h1 { class = "slim", img { src = "/wolf.png", width = "32", height = "32" }, "Were Wolf" },
            div { id = "app", class = "game " .. (kind or "client"), p { "Loading..." } },
            script { CLIENT_JS },
        },
    }
end

return M
